--
-- NextDR Supabase Database Schema 
-- NDR-SCHEMA-VERSION: 1.1.6
-- NDR-UPGRADE-FROM: 1.1.5
-- NDR-SCHEMA-TYPE: INCR
-- NDR-FULL-BASELINE-SCHEMA-SHA256: cff573c59fbb66c8f424eacfdb9e194e9d0357df5d9bb7b88b42f1fa82db5e5c
-- NDR-FULL-UPGRADE-SCHEMA-SHA256: 2d0680a79c3f1c85d7c1d291912bf222dcc9033ad5d6c64be1040cf0f631e16d
--

create table "public"."execution_run_reports" (
    "id" uuid not null default gen_random_uuid(),
    "run_id" text not null,
    "report_json" jsonb not null,
    "report_hash" text not null,
    "pdf_path" text not null,
    "report_version" text not null default '1.0.0'::text,
    "schema_version" text not null default '1.0.0'::text,
    "generated_at" timestamp with time zone not null default now(),
    "immutable" boolean not null default true
);


alter table "public"."execution_run_reports" enable row level security;

create table "public"."twilio_settings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "account_sid" text not null default ''::text,
    "auth_token" text not null default ''::text,
    "from_number" text not null default ''::text,
    "enabled" boolean not null
);


alter table "public"."twilio_settings" enable row level security;

CREATE UNIQUE INDEX execution_run_reports_pkey ON public.execution_run_reports USING btree (id);

CREATE UNIQUE INDEX execution_run_reports_run_id_key ON public.execution_run_reports USING btree (run_id);

CREATE INDEX idx_execution_run_reports_generated_at ON public.execution_run_reports USING btree (generated_at DESC);

CREATE INDEX idx_execution_run_reports_run_id ON public.execution_run_reports USING btree (run_id);

CREATE UNIQUE INDEX twilio_settings_pkey ON public.twilio_settings USING btree (id);

alter table "public"."execution_run_reports" add constraint "execution_run_reports_pkey" PRIMARY KEY using index "execution_run_reports_pkey";

alter table "public"."twilio_settings" add constraint "twilio_settings_pkey" PRIMARY KEY using index "twilio_settings_pkey";

alter table "public"."execution_run_reports" add constraint "execution_run_reports_run_id_key" UNIQUE using index "execution_run_reports_run_id_key";

create policy "Authenticated users can delete execution_run_reports"
on "public"."execution_run_reports"
as permissive
for delete
to authenticated
using ((role() = 'authenticated'::text));


create policy "Authenticated users can insert execution_run_reports"
on "public"."execution_run_reports"
as permissive
for insert
to authenticated
with check ((role() = 'authenticated'::text));


create policy "Authenticated users can read execution_run_reports"
on "public"."execution_run_reports"
as permissive
for select
to authenticated
using ((role() = 'authenticated'::text));


create policy "Authenticated users can update execution_run_reports"
on "public"."execution_run_reports"
as permissive
for update
to authenticated
using ((role() = 'authenticated'::text))
with check ((role() = 'authenticated'::text));


create policy "Authenticated users can delete Twilio settings"
on "public"."twilio_settings"
as permissive
for delete
to authenticated
using ((role() = 'authenticated'::text));


create policy "Authenticated users can insert Twilio settings"
on "public"."twilio_settings"
as permissive
for insert
to authenticated
with check ((role() = 'authenticated'::text));


create policy "Authenticated users can read Twilio settings"
on "public"."twilio_settings"
as permissive
for select
to authenticated
using ((role() = 'authenticated'::text));


create policy "Authenticated users can update Twilio settings"
on "public"."twilio_settings"
as permissive
for update
to authenticated
using ((role() = 'authenticated'::text))
with check ((role() = 'authenticated'::text));
